import React from 'react';
import { useSystem } from '../../context/SystemContext';
import { AlertOctagon, CheckCircle2, ShieldAlert } from 'lucide-react';

export const IncidentsView: React.FC = () => {
  const { incidents, resolveIncident } = useSystem();

  return (
    <div className="p-6 space-y-6 text-slate-100 max-w-7xl mx-auto animate-fadeIn font-mono">
      {/* Header */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 bg-[#0e1424] p-4 rounded-xl border border-slate-800">
        <div>
          <div className="flex items-center gap-2">
            <AlertOctagon className="w-5 h-5 text-red-400" />
            <h2 className="text-xl font-bold text-slate-100">INCIDENT COMMAND & REASONING LOG</h2>
            <span className="text-xs text-red-400 bg-red-950/60 px-2 py-0.5 rounded border border-red-800">
              {incidents.filter((i) => i.status !== 'Resolved').length} ACTIVE
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Real-time critical infrastructure incident tickets generated by the Trust-Aware Intelligence Fabric.
          </p>
        </div>
      </div>

      {/* Incidents List */}
      <div className="space-y-4">
        {incidents.map((inc) => (
          <div key={inc.id} className="p-5 bg-[#0e1424] border border-slate-800 rounded-xl space-y-3">
            <div className="flex items-center justify-between border-b border-slate-800 pb-2">
              <div className="flex items-center gap-2">
                <span className="font-bold text-red-400 text-sm">{inc.code}</span>
                <span className="text-xs text-cyan-300 font-bold bg-slate-900 px-2 py-0.5 rounded border border-slate-800">
                  {inc.assetName}
                </span>
              </div>
              <span className={`px-2.5 py-1 text-xs font-bold rounded ${inc.status === 'Resolved' ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/40' : 'bg-red-500/20 text-red-400 border border-red-500/40 animate-pulse'}`}>
                {inc.status}
              </span>
            </div>

            <h3 className="text-base font-bold text-slate-100">{inc.title}</h3>
            <p className="text-xs text-slate-300 leading-relaxed">{inc.description}</p>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs pt-2 border-t border-slate-800/80">
              <div>Detected: <strong className="text-slate-200">{inc.detectedAt}</strong></div>
              <div>Root Cause: <strong className="text-amber-300">{inc.rootCauseCategory}</strong></div>
              <div>RC at Trigger: <strong className="text-red-400">{inc.realityConfidenceAtTrigger}%</strong></div>
              <div>Trust Score: <strong className="text-amber-400">{inc.trustScoreAtTrigger}%</strong></div>
            </div>

            {inc.status !== 'Resolved' && (
              <div className="pt-2 text-right">
                <button
                  onClick={() => resolveIncident(inc.id)}
                  className="px-3 py-1.5 bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 border border-emerald-500/40 rounded text-xs font-bold transition-all"
                >
                  MARK AS MITIGATED & RESOLVED
                </button>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};
